# 开启swagger，SwaggerConfig 配置
swagger:
  enable: false

logging:
    level:
        ROOT: info 
        cc.wanforme.coorush: info

# 数据源, alibaba druid连接池
spring:
  aop:
    proxy-target-class: true    auto: true  datasource:#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        # druid 通用配置， 也可以在各个数据源中单独配置
       max-active: 20  # 最大数量
       initial-size: 2 # 初始化数量
       max-wait: 60000 # 获取连接超时等待时间
       min-idle: 1 # 最小闲置数量
       time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
       min-evictable-idle-time-millis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒 
       validation-query: SELECT 1 FROM DUAL
       test-while-idle: true
       test-on-borrow: false
       test-on-return: false
       # 打开PSCache，并且指定每个连接上PSCache的大小 
       pool-prepared-statements: true
       # max-open-prepared-statements: 20
       max-pool-prepared-statement-per-connection-size: 20
       # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙  
       filters: stat,wall,log4j
       # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
       connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

       # 主数据源
       default:
          url: jdbc:mysql://localhost:3306/www.wanforme.cc?useUnicode=true&characterEncoding=UTF-8&atuoReconnect=true
          username: root
          password: passswordpassword
          driver-class-name: com.mysql.jdbc.Driver
#       db2:
#          url: jdbc:oracle:thin:@192.168.136.222:ORCL
#          username: sa
#          password: sa123456
#          driver-class-name: oracle.jdbc.OracleDriver


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: cc.wanforme.coorush.base.po
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰命名
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # sql日志输出

