logging:
    level:
        ROOT: info 
        cc.wanforme.nukkit: info
        
nukkit:  spring:
    # 启用 nukkit 相关模块
    # enable nukkit module    enable: true
    # 是否一同启动 nukkit
    # run nukkit after launch app
    start-nukkit: true
    # 使用 spring 编写的 nukkit 插件位置
    # plugins' location written with spring
    nukkit-spring-plugin-location: nsplugins

