server:
  port: 8050 #web端口
  servlet:
    context-path: /sd
    application-display-name: StartDemo
  shutdown: graceful # 优雅关机(勿强制杀死进程)

spring:
  profiles:
    active: dev
  application:
    name: StartDemo
#  cloud:
#    config:
#      enabled: false

# 日志文件位置
logging:
  config: classpath:log4j2-spring.xml # 指定日志配置文件
  level:
    cn.jay.repository: trace
 
 
 